### ISSUE TITLE
In StashboxMultitenantMiddleware the new RequestServicesFeature is not disposed

### ISSUE THREAD

**Issue by adambajguz** [z4kn4fein/stashbox-extensions-dependencyinjection#10]
In https://github.com/z4kn4fein/stashbox-extensions-dependencyinjection/blob/684c52f3506b134049496f7afb465db0380d5916/src/stashbox.aspnetcore.multitenant/StashboxMultitenantMiddleware.cs#LL56C64-L56C86 the created `RequestServicesFeature` is not disposed.

**Comment by z4kn4fein** [comment]
Hi @adambajguz, thank you for reporting, I'm going to fix this!

**Comment by z4kn4fein** [comment]
@adambajguz The fix is published in `v5.2.1`.
