### ISSUE TITLE
Additional registration in Generic Host

### ISSUE THREAD

**Issue by vnvizitiu** [z4kn4fein/stashbox-extensions-dependencyinjection#12]
Hello,

I'm trying to compose some composition roots in a generic hosted application, so it's a bit harder to explain but I also found where my issue might be.

So this is the code I'm using

```
public class Program
{
    public static async Task Main(string[] args)
    {
        IHostBuilder builder = Host.CreateDefaultBuilder(args);
        builder.UseEnvironment(Environments.Development);
        builder.ConfigureServices((context, collection) =>
        {
            if (args.Contains("--info"))
            {
                collection.AddHostedService<ShowInfoHostedService>();
            }
        });
        ConfigureHost(builder);
        IHost host = builder.Build();
        await host.RunAsync();
    }

    private static void ConfigureHost(IHostBuilder builder)
    {
        builder.ConfigureContainer<IStashboxContainer>((context, container) =>
        {
            if (context.HostingEnvironment.IsDevelopment())
            {
                container.Validate();
            }
        });
        builder.UseStashbox(container =>
        {
            container.RegisterInstance(container);
            container.ComposeAssembly(typeof(Program).Assembly);
        });
    }
}
```

And the composition root in question looks like this

```
public void Compose(IStashboxContainer container)
{
   AppSettings appSettings = container.Resolve<IConfigurationRoot>().Get<AppSettings>()!;
   container.RegisterInstance(appSettings);
}
```

What I found is that in the StashboxServiceCollectionExtensions in the Stashbox.Extensions.DependencyInjection package the following code

```
    private static IStashboxContainer PrepareContainer(IServiceCollection services,
        Action<IStashboxContainer>? configure = null, IStashboxContainer? stashboxContainer = null)
    {
        var container = stashboxContainer ?? new StashboxContainer();

        container.Configure(config => config
#if HAS_KEYED
            .WithUniversalName(KeyedService.AnyKey)
            .WithAdditionalDependencyAttribute<FromKeyedServicesAttribute>()
            .WithAdditionalDependencyNameAttribute<ServiceKeyAttribute>()  
#endif
            .WithDisposableTransientTracking()
            .WithRegistrationBehavior(Rules.RegistrationBehavior.PreserveDuplications));

        configure?.Invoke(container);

        container.RegisterInstance<IServiceScopeFactory>(new StashboxServiceScopeFactory(container));
        container.Register<IServiceProvider, StashboxServiceProvider>(c => c
                .WithFactory(r => new StashboxServiceProvider(r))
#if HAS_IS_SERVICE
                .AsServiceAlso<IServiceProviderIsService>()
#endif
#if HAS_KEYED
                .AsServiceAlso<IServiceProviderIsKeyedService>()
#endif
        );

        container.RegisterServiceDescriptors(services);

        return container;
    }
```

The issue is as follows, I need access to some of the items registered in the service collection (the `IConfigurationRoot`), but there is no way (that I found) for me to run my compositions after the `container.RegisterServiceDescriptors(services);` in this scenario, because if I do run it in the `UseStashbox` method, that will run before the registry of the service descriptors from the service collection.

Is there a different way of handling this? If not, would it be possible to add a hook before returning the container in the code mentioned above so that I can do registrations while still having access to the previously registered items?

I admit I don't know the volume of work this would imply but being able to do all the registrations before the host is being run would be beneficial, especially since quite a bit of configuration would be done during those assembly compositions since each project brings a bit of configuration to the table. 

To give you an example, before this I used the "naked" stashbox container, I would create my own IConfigurationBuilder and register it, and then resolve it in the many composition roots across projects to add specific configuration points like this:

```
 IConfigurationRoot configurationRoot = BuildConfiguration();
 container.RegisterInstance(configurationRoot);

private IConfigurationRoot BuildConfiguration()
{
    IConfigurationBuilder configurationBuilder = new ConfigurationBuilder();
    configurationBuilder.SetBasePath(GetBasePath);
    configurationBuilder.AddEnvironmentVariables("AutomationScripts_");
    configurationBuilder.AddJsonFile("appsettings.json", true, true);
    configurationBuilder.AddUserSecrets(Assembly.GetExecutingAssembly(), true
    string[] commandLineArguments = Environment.GetCommandLineArgs().Skip(1).
    if (commandLineArguments.Any())
    {
        configurationBuilder.AddCommandLine(commandLineArguments);
    }
    return configurationBuilder.Build();
}

private void RegisterOptions(IStashboxContainer container)
{
    IConfigurationRoot configurationRoot = container.Resolve<IConfigurationRoot>();
    IServiceCollection serviceCollection = new ServiceCollection();
    serviceCollection.Configure<EmailOptions>(
        configurationRoot.GetSection(nameof(EmailOptions)));
    container.RegisterServiceDescriptors(serviceCollection);
}

```

The reason this came up was that we would like to migrate from a console app to a hosted service to have access to all of the other services provided by the Generic Host

**Comment by vnvizitiu** [comment]
Seems that I got it to work by putting the composition inside the `ConfigureContainer`, let me know if you want me to close this issue or leave it in case it's something worth looking into

**Comment by z4kn4fein** [comment]
Hi @vnvizitiu, thank you for reporting this issue! I'm happy you have found the solution. I'd have suggested the same. `ConfigureContainer` is called after the container is built up and before the app starts, so it seems a good place for executing the compose which has dependencies on core services.

Let me know if you still have issues or if you need help with anything.

**Comment by vnvizitiu** [comment]
Thanks for the reply, I'm good now, guess we can close this one, thanks again 😄
