### ISSUE TITLE
Improper choice of base constructor in StashboxServiceDescriptor

### ISSUE THREAD

**Issue by lyra95** [z4kn4fein/stashbox-extensions-dependencyinjection#13]
Hello,

https://github.com/z4kn4fein/stashbox-extensions-dependencyinjection/blob/5b15c228f9e5c57ec2da2d617b480357a1c85a80/src/stashbox.extensions.dependencyinjection/StashboxServiceDescriptor.cs#L12

Apparently this `base(DescriptorType, DescriptorType)` references to `ServiceDescriptor(Type serviceType, object instance)`. `ServiceDescriptor(Type serviceType, Type implementationType, ServiceLifetime lifetime)` should be used instead I think.

Found this issue when updating to `Stashbox.Extensions.Hosting v5.5.2`. Some unit tests in my project is failing due to the issue, but It doesn't seem to be critical though.

**Comment by z4kn4fein** [comment]
Hi @lyra95, thank you for reporting this issue! I've published the fix in `v5.5.3`. Just out of curiosity, may I ask what kind of issue this caused?

**Comment by lyra95** [comment]
I have a unit tests which scrapes all registrations and their usages, to check whether null-ability contexts are met (e.g. if one is registered as Foo<Bar?>, its user must resolves it with Foo<Bar?> not Foo\<Bar\>). This issue caused some issue on null-ability context inferencing of the type StashboxServiceDescriptor.(since they are registered as well). I ruled them out to pass the test but thought it would be good to report here.

Thanks for the quick fix!
