### ISSUE TITLE
Question: Is there a way to interact with the container from the StashboxServiceProvider

### ISSUE THREAD

**Issue by vnvizitiu** [z4kn4fein/stashbox-extensions-dependencyinjection#4]
Hello,

I was wondering if I can use the container methods (like WireUp and BuildUp), aside from `Resolve` when getting the StashboxServiceProvider via IServiceProvider.

Mostly interested in this for unit testing.

Thanks,
Vlad V.

**Comment by z4kn4fein** [comment]
Hi,

The `BuildUp` is on the `IDepenedencyResolver` interface which can be requested from the `IServiceProvider` by calling the `GetService(typeof(IDepenedencyResolver))`. 

If you want to use them in unit tests mostly you can check the tests of this [sample app](https://github.com/z4kn4fein/stashbox-extensions-dependencyinjection/tree/master/sample), it uses one of the Mocking extensions for Stashbox which allows accessing the underlying Stashbox container (for WireUp) and also can used for auto mocking.

Let me know if you have any more questions, or suggestions!
Thanks!

**Comment by vnvizitiu** [comment]
Thank you for the clarification and the quick response.
