### ISSUE TITLE
Stashbox.AspNetCore.Hosting and netcoreapp3.0

### ISSUE THREAD

**Issue by 0x15e** [z4kn4fein/stashbox-extensions-dependencyinjection#5]
I'm in the process of migrating an AspNetCore 2.2 app to 3.0 and part of the process is replacing [WebHostBuilder with HostBuilder](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#hostbuilder-replaces-webhostbuilder). 

The new code in `CreateHostBuilder(string[] args)` now looks like this:
```
        public static IHostBuilder CreateHostBuilder(String[] args)
        {
            return Host
                .CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(
                    webBuilder => webBuilder
                        .UseStartup<Startup>()
                        .UseStashbox());
        }
```

The app currently uses the `ConfigureContainer(IStashboxContainer container)` method of configuring stashbox and performing advanced DI registration but it appears that this method has special meaning to netcoreapp3.0. When the app starts, it immediately crashes with an `InvalidCastException` trying to cast `Microsoft.Extensions.DependencyInjection.ServiceCollection` to `Stashbox.IStashboxContainer`. Adding a new overload of `ConfigureContainer` that takes an `IServiceCollection` causes an `InvalidOperationException` about not allowing multiple overloads of `ConfigureContainer` and removing `ConfigureContainer` entirely allows the app to start.

I haven't yet tried using `Stashbox.Extensions.Hosting` with the generic host but that will be next. I expect that will ultimately be the best solution since the intent appears to be to deprecate and eventually replace `WebHostBuilder` with `HostBuilder`. 

What are your thoughts on this?

**Comment by z4kn4fein** [comment]
Hey,

I checked and you are right, the `WebHostBuilder` part is not working correctly with AspNetCore 3.0, but the `Stashbox.Extensions.Hosting` package resolves this issue. You can change your configuration like this:
```
public static IHostBuilder CreateHostBuilder(String[] args)
{
    return Host.CreateDefaultBuilder(args)
        .UseStashbox()
        .ConfigureWebHostDefaults(
            webBuilder => webBuilder
                .UseStartup<Startup>());
}
```
I'll update the documentation with this.

Thanks for pointing out! If you have more questions or issues please let me know!

**Comment by 0x15e** [comment]
Yep, looks like going with the generic host is the best way forward and everything works fine that way. Thanks for checking into it!
